import os
import sys

_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _root not in sys.path:
    sys.path.insert(0, os.path.dirname(_root))

from AICode.MarcoAPI.BaoStockAPI import UPDATE_TRADING_DATES, UPDATE_ADJUST_FACTOR_DATA, UPDATE_ORIGIN_DATA, FREQUENCY_5M, FREQUENCY_1D
from AICode.MarcoAPI.Converter import SZ200_ORIGIN_XLSX2CONFIG, SZ200_ORIGIN_XLSX2DATA, SZ200_ORIGIN_1D_TO_ORIGIN_FRONT_1D, SZ200_ORIGIN_5M_TO_ORIGIN_FRONT_5M, SZ200_ORIGIN_FRONT_1D_TO_1D, SZ200_ORIGIN_FRONT_5M_TO_5M, DEFAULT_WORKERS

def UPDATE_ORIGIN_DATA_1D():
    UPDATE_ORIGIN_DATA(frequency=FREQUENCY_1D)

def UPDATE_ORIGIN_DATA_5M():
    UPDATE_ORIGIN_DATA(frequency=FREQUENCY_5M)

# SZ200.xlsx 转换为 SZ200.config
def SZ200_ORIGIN_XLXS_TO_CONFIG():
    SZ200_ORIGIN_XLSX2CONFIG()

# SZ200.xlsx 转换为 SZ200.DATA
def SZ200_ORIGIN_XLSX_TO_DATA():
    SZ200_ORIGIN_XLSX2DATA()

def UPDATE_ADJUST_FACTOR():
    UPDATE_ADJUST_FACTOR_DATA()

def ORIGIN_1D_TO_ORIGIN_FRONT_1D(workers: int=DEFAULT_WORKERS):
    SZ200_ORIGIN_1D_TO_ORIGIN_FRONT_1D(workers)

def ORIGIN_5M_TO_ORIGIN_FRONT_5M(workers: int=DEFAULT_WORKERS):
    SZ200_ORIGIN_5M_TO_ORIGIN_FRONT_5M(workers)

def ORIGIN_FRONT_1D_TO_1D(workers: int=DEFAULT_WORKERS):
    SZ200_ORIGIN_FRONT_1D_TO_1D(workers)
    
def ORIGIN_FRONT_5M_TO_5M(workers: int=DEFAULT_WORKERS):
    SZ200_ORIGIN_FRONT_5M_TO_5M(workers)

if __name__ == "__main__":
    UPDATE_TRADING_DATES()
    UPDATE_ADJUST_FACTOR()
    UPDATE_ORIGIN_DATA_1D()
    UPDATE_ORIGIN_DATA_5M()
    ORIGIN_1D_TO_ORIGIN_FRONT_1D()
    ORIGIN_5M_TO_ORIGIN_FRONT_5M()
    ORIGIN_FRONT_1D_TO_1D()
    ORIGIN_FRONT_5M_TO_5M()
